Encryption Manager Initialised in init() method
iamMehedi/Secured-Preference-Store pull request #14
Opened 2017-08-06 11:39 UTC by StuStirling

I have move the initialisation of the encryption manager into a method called init(). This method should be called only once before calling any other method on the store. The reason behind this is to have error handling in one place rather than everywhere you try and get the store instance using getSharedInstance(). This will be a breaking change however so thought needs to go into whether this is a library change like I am proposing in this pull request or if it's an implementation details that would be useful to highlight in the README.

I have made a couple of modifications to the Git project structure to allow contributors to quickly and easily checkout the project without having to add files: namely the settings.gradle file has been added to the git repo and a .gitignore file added.

2017-08-07 06:06 UTC, iamMehedi requested changes

2017-08-07 06:06 UTC, iamMehedi commented on .gitignore
> +# Created by .ignore support plugin (hsz.mobi)
needs to be cleaned up to contain only the Intellij/Android Studio stuff. something like this might suffice
```
*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
/captures
```

2017-08-07 06:47 UTC, iamMehedi requested changes
Thanks for the pull request. Please review the changes requested and make changes accordingly.

2017-08-07 06:47 UTC, iamMehedi commented on .idea/copyright/profiles_settings.xml
> +<component name="CopyrightManager">
IMO this doesn't need to be in source control. A shared gradle project should have no IDE specific preferences stored on VCS unless its a must have setting to build the project.

2017-08-07 06:47 UTC, iamMehedi commented on .idea/markdown-navigator.xml
> +<?xml version="1.0" encoding="UTF-8"?>
IMO doesn't need to be in VCS

2017-08-07 06:47 UTC, iamMehedi commented on .idea/markdown-navigator/profiles_settings.xml
> +<component name="MarkdownNavigator.ProfileManager">
IMO doesn't need to be in VCS

2017-08-07 06:47 UTC, iamMehedi commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
IMO doesn't need to be in VCS

2017-08-07 06:47 UTC, iamMehedi commented on securedpreferencestore/src/main/java/devliving/online/securedpreferencestore/SecuredPreferenceStore.java
> +    public static void init( Context appContext) throws IOException, CertificateException, NoSuchAlgorithmException, KeyStoreException, UnrecoverableEntryException, InvalidAlgorithmParameterException
IMO it'd be better to take in a recovery handler when initializing, so the `init` should be 
```java
public static void init(Context appContext, @Nullable RecoveryHandler recoveryHandler){
    setRecoveryHandler(recoveryHandler);
    ...
}
```

2017-08-07 06:47 UTC, iamMehedi commented on securedpreferencestore/src/main/java/devliving/online/securedpreferencestore/SecuredPreferenceStore.java
> +    private void checkInitCalled() {
This method is unnecessary as there is no way to have a non-null `SecuredPreferenceStore` instance unless the `init` was called and successful.

2017-08-07 06:47 UTC, iamMehedi commented on securedpreferencestore/src/main/java/devliving/online/securedpreferencestore/SecuredPreferenceStore.java
> +        checkInitCalled();
I can not think of a scenario where this check should be necessary.

2017-08-08 20:19 UTC, StuStirling commented on .gitignore
> +# Created by .ignore support plugin (hsz.mobi)
That works for the project level .gitignore file but I think more should be added to ignore the user specific .idea files you have commented below. I will update accordingly.

2017-08-08 20:33 UTC, StuStirling commented
Hi Mehedi, please see the changes you requested in the last commit

2017-08-09 06:36 UTC, iamMehedi approved these changes

2017-08-09 06:37 UTC, merged